### PR TITLE
Move to pure function component and allow multiple element types

### PR DESCRIPTION
**Pull request by onedesert**

### CODE REVIEW

**Comment by rwu823** [comment]
Hi, what is this advantage?

**Comment by onedesert** [comment]
Using pure function on a stateless component you will improve in performance. The type will allow to use this component for "ul" list as well.

**Comment by rwu823** [comment]
@onedesert 
Well done, I like custom `type` with a tag. It will be implemented in next version.

A question for performance between `stateless` function and `shouldCopmonentUpdate`. Which one is better?

Reference:
http://programmers.stackexchange.com/questions/302844/how-will-react-0-14s-stateless-components-offer-performance-improvements-withou

**Comment by rwu823** [comment]
https://github.com/rwu823/react-tag/issues/2

**Pull request closed without merging**
